name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android_build:
    name: Android build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install npm packages
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Generate Android project
        run: npx expo prebuild --platform android --clean

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4 # speeds up build by caching

      - name: Gradle build
        run: cd android && chmod +x gradlew && ./gradlew :app:assembleRelease -PreactNativeArchitectures=arm64-v8a --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android_build_release
          path: ${{ github.workspace }}/android/app/build/outputs/apk/release/*.apk
